compatibility with vcpkg
Russian-Doom/russian-doom pull request #418
Opened 2023-01-10 04:14 UTC by rfomin

* Move FindSDL2* to cmake/SDL2 directory, rename targets.

* Add vcpkg.json with dependencies.

The only problem is that the contents of the base directory are not copied to the target directory, not sure why.

2023-01-11 05:48 UTC, Dasperal requested changes
* Vcpkg automatically copies DLLs to the exe directory, so copying of the provided DLLs should be disabled in `/lib/DLL/CMakeLists.txt` for vcpkg mode.
* If vcpkg doesn't provide install rules for DLLs, they must be provided manually, probably in the same `/lib/DLL/CMakeLists.txt`.
* Add "1.c: Using VCPKG as dependency provider" ("1.b" is for MSVC env) section to COMPILING.md with guide how to set up and use vcpkg. Also add necessary guidelines to the other sections.
* `miniz` can also be obtained using vcpkg.

2023-01-11 05:48 UTC, Dasperal commented on CMakeLists.txt
> +
* Why this was moved under the `project(...)` directive?
* [Cmake documentation](https://cmake.org/cmake/help/latest/guide/using-dependencies/index.html#find-module-files) says that `CMAKE_MODULE_PATH` can be provided by the user, so I think we should always `list(APPEND CMAKE_MODULE_PATH ...)` instead of `set(CMAKE_MODULE_PATH ...)`
* Why SDL2 finders are disabled in the vcpkg manifest mode? To use configs provided by vcpkg? But why not use them in non-manifest mode? `libsamplerate` and `miniz` can also come from vcpkg, so why their finders are always enabled?  
I suggest modifying finders to make them able to find libraries in the vcpkg environment. Or run `find_package` in the `CONFIG` mode for vcpkg environment.

2023-01-11 05:48 UTC, Dasperal commented on CMakeLists.txt
> +set(SDL2_MAIN_LIBRARY "$<TARGET_NAME_IF_EXISTS:SDL2::SDL2main>")
If vcpkg config doesn't have `SDL2_MAIN_LIBRARY` variable, it is better to update check at linking side to make it work against `SDL2::SDL2main` target properties.

2023-01-11 05:48 UTC, Dasperal commented on vcpkg.json
> +    "sdl2-mixer",
Is plain `sdl2-mixer` enough for MIDI, MP3, FLACK, MOD, OGG and Opus playback? Official builds of SDL2_mixer provide support for MOD, OGG and Opus with additional DLLs. Does vcpkg provide those DLLs or compiles support for those formats into the main `sdl2-mixer` DLL?

2023-01-11 05:48 UTC, Dasperal commented on vcpkg.json
> +    "sdl2-net",
`sdl2-net` names its config `sdl2-net` but find_package searches for `sdl2_net`, so configuration fails.

2023-01-11 05:51 UTC, Dasperal commented
Last time I tried vcpkg, SDL2 DLL from it caused crush at startup, was it fixed?

2023-01-11 06:08 UTC, rfomin commented on CMakeLists.txt
> +
> * Why SDL2 finders are disabled in the vcpkg manifest mode? To use configs provided by vcpkg?

Yes, to use configs provided by vcpkg.

>  But why not use them in non-manifest mode?

Ok, I guess we can check `VCPKG_INSTALLED_DIR` for example. I'm not sure what variable to test.

> * `libsamplerate` and `miniz` can also come from vcpkg, so why their finders are always enabled?

vcpkg do not provide finders for these packages.

2023-01-11 06:10 UTC, rfomin commented on vcpkg.json
> +    "sdl2-mixer",
We can add this for MOD and OPUS:
```
    {
      "name": "sdl2-mixer",
      "features": [ "libmodplug", "opusfile" ]
    },
```
OPUS don't work currently, it will be fixed in the next version of SDL_mixer.

2023-01-11 06:11 UTC, rfomin commented
> * If vcpkg doesn't provide install rules for DLLs, they must be provided manually, probably in the same `/lib/DLL/CMakeLists.txt`.

There is an option to provide automatic install, works in Woof: 
```cmake
# X_VCPKG_APPLOCAL_DEPS_INSTALL automatically installs dependencies
# (except SDL_Mixer "plugins"). CMP0077 supress some arcane CMake warning.
set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)
set(X_VCPKG_APPLOCAL_DEPS_INSTALL ON)
```

> Last time I tried vcpkg, SDL2 DLL from it caused crush at startup, was it fixed?

It works for me, I use it to test resent PRs.

2023-01-11 07:04 UTC, Dasperal commented on vcpkg.json
> +    "sdl2-net",
My bad, used outdated vcpkg. In 2022.11.14 it is named correctly.

2023-01-11 07:12 UTC, rfomin commented on CMakeLists.txt
> +
> * Why this was moved under the `project(...)` directive?

Not all vcpkg variables are set before `project(...)`.

> we should always list(APPEND CMAKE_MODULE_PATH ...)

Fixed in https://github.com/JNechaevsky/inter-doom/pull/418/commits/79a5a808673645ba44ef12b427a528c30ceba1a2

> `miniz` ...

But we already have this in our project, I thought that was the purpose of single file libraries?

2023-01-11 07:15 UTC, rfomin commented on CMakeLists.txt
> +set(SDL2_MAIN_LIBRARY "$<TARGET_NAME_IF_EXISTS:SDL2::SDL2main>")
I don't know how to fix this, sorry! In general, I'm not good with CMake, so feel free to close this PR or modify it as you see fit. I just did this to build it in my vcpkg + MSVC environment.

2023-01-11 09:26 UTC, rfomin commented
@Dasperal Not relevant to this PR, but I found out how to fix slow libsamplerate from vcpkg, see: https://github.com/fabiangreffrath/woof/commit/cde9dd6aeca1c1d91bd6ddee550714d9e8055ee7

2023-01-11 11:43 UTC, Dasperal commented on CMakeLists.txt
> +set(SDL2_MAIN_LIBRARY "$<TARGET_NAME_IF_EXISTS:SDL2::SDL2main>")
Done in 964bdba5db87f4cbffe77ccd1b985a2dbb0b7a51

2023-01-11 11:48 UTC, Dasperal commented on vcpkg.json
> +    "sdl2-mixer",
On my side, OPUS music works with official SDL_mixer 2.6.1

2023-01-11 12:17 UTC, rfomin commented on vcpkg.json
> +    "sdl2-mixer",
Yes it works in official version but not in vcpkg, not sure: https://github.com/microsoft/vcpkg/issues/15335

2023-01-11 12:47 UTC, Dasperal commented on CMakeLists.txt
> +
> vcpkg do not provide finders for these packages.

It provides configs for those packages, though before cd5cdfe8b9e07af62aecefc13100afa6010edd4d we searched for wrong names and used wrong variables to check if packages were found before 5bd8925b95a60f2e8024b8d4c3c5142db7591f19

> But we already have this in our project, I thought that was the purpose of single file libraries?

The purpose of `miniz` is to replace `libpng` and `zlip`. We vendor it because the only environment that have it externally is vcpkg and Fedora Linux.

> Yes, to use configs provided by vcpkg.

Then I think it is better to use `find_package` in `CONFIG` mode for vcpkg environment instead of disabling find-modules.

2023-01-11 12:54 UTC, rfomin commented on CMakeLists.txt
> +
> we searched for wrong names and used wrong variables

Wait, CMake is case sensitive? I did not know. So if we write `find_package(... CONFIG)` will it use the vcpkg find modules first?

2023-01-11 13:09 UTC, Dasperal commented on CMakeLists.txt
> +
> Wait, CMake is case sensitive?

Looks like yes, at least in some cases. I checked with cmake debug: `MINIZ_FOUND` is not set, but `miniz_FOUND` is `1`.

> So if we write find_package(... CONFIG) will it use the vcpkg find modules first?

It will skip find modules and search for configs only ([Documentation](https://cmake.org/cmake/help/latest/command/find_package.html#full-signature)). Vcpkg provides configs, not find modules.

2023-01-11 13:18 UTC, rfomin commented on CMakeLists.txt
> +
> The CONFIG option, the synonymous NO_MODULE option ...

Wow, I totally missed that! Thanks, I'll try to fix it in a few hours.

2023-01-11 17:28 UTC, rfomin commented on CMakeLists.txt
> +
I use [CMAKE_FIND_PACKAGE_PREFER_CONFIG](https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_PACKAGE_PREFER_CONFIG.html), it seems to work.

2023-01-11 17:43 UTC, rfomin commented on CMakeLists.txt
> +
Hmm, I don't know why MSYS2 gcc is failing.

2023-01-11 19:22 UTC, Dasperal commented on CMakeLists.txt
> +
> Hmm, I don't know why MSYS2 gcc is failing.

Because SDL2_mixer config doesn't interface link to SDL2 in opposite to our SDL2_mixer finder. SDL2_mixer itself also link SDL2 privately, and our SDL2_mixer finder doesn't check if SDL2 exists. Don't know why Clang is working, though.
So I think we need to remove linking from SDL2_mixer finder and link to SDL2 explicitly.

I'll add this change and clean up the branch.

2023-01-12 13:04 UTC, Dasperal commented
So, what's left:
* Add copy target to `/lib/DLL/CMakeLists.txt` for transitive dependencies from vcpkg if they exist (SDL_Mixer "plugins").
* Add install rules for transitive dependencies from vcpkg if they exist (SDL_Mixer "plugins").
Also consider manually adding install rules for direct dependencies from vcpkg as well, because vcpkg install them multiple times, one for each executable, and doesn't print what is installed and where.
* Add guide about using vcpkg to COMPILING.md.

Other questions:
* Do we want to always prioritize configs over find modules?
  * In some cases, user may want to provide his own development libraries using variables like `SDL2_DIR` that take effect only in find module.
  * The `find_package` in the config mode doesn't print any information if it managed to find the package. In the module mode, it displays the version of found package.
* Do we want to use `miniz` from vcpkg?
On Fedora Linux, we probably want to use global `miniz` because it can be shared between packages, and have a newer version than the vendored one. But I am not sure about vcpkg, `miniz` there is already outdated, and it will be just another DLL for no reason.

2023-01-12 14:27 UTC, rfomin commented
> * vcpkg install them multiple times, one for each executable, and doesn't print what is installed and where.

This is not a problem for me, in fact I would like to reduce the number of unnecessary messages. I like it when a program prints only error messages or "done". 😄 

> * Do we want to always prioritize configs over find modules?

We can make `option(CMAKE_FIND_PACKAGE_PREFER_CONFIG On)` (I don't remember exact syntax).

> * Do we want to use `miniz` from vcpkg?

Personally, I like single-file libraries because we don't have to manage dependencies.

2023-01-15 09:59 UTC, JNechaevsky commented
Colleagues, is it release-critical? I'm thinking to release a quad-res update today.

2023-01-15 10:16 UTC, Dasperal commented
No, it's not release-critical. Just support for another optional building environment.

2023-02-09 15:05 UTC, Dasperal commented
* I decided that we will prioritize our `miniz` over one from vcpkg by default (not include it in vcpkg manifest or building guide).
* Exposed `CMAKE_FIND_PACKAGE_PREFER_CONFIG` as a cmake option.
* Exposed `VCPKG_MANIFEST_MODE` as a cmake option to let the user choose to operate in manifest mode or classic mode.
* Added guide about compiling with MSVC and vcpkg.
* Added CI builds with MSVC. Temporary disabled to save GitHub Actions time because they are currently not needed for anything.

And while I'm here, update libraries.

I'll leave TODOs for copy target and install rules for now and merge that already done.
I probably file a feature request to vcpkg about automatic copy and install of transitive dependencies.

2023-02-09 15:05 UTC, Dasperal approved these changes

2023-02-09 15:06 UTC, merged

2023-02-09 16:29 UTC, rfomin commented on .github/workflows/continuous-integration.yml
> +#         vcpkg install --triplet=${{ matrix.arch.msvc_triplet }} sdl2 sdl2-mixer[core,nativemidi,libmodplug,opusfile] sdl2-net libsamplerate
The problem is that vcpkg does not support the WinXP toolkit: https://github.com/microsoft/vcpkg/issues/1015
I have found that binary caching and NuGet are the best way to prevent rebuilding from scratch: https://github.com/fabiangreffrath/woof/blob/4d5adaf346d6d62b1b8fbb1535b6003540929e8d/.github/workflows/win_msvc.yml#L26 It may not be necessary for Inter Doom, Woof has a heavy dependency on FluidSynth, at least 30 minutes of CI build.

2023-02-10 06:26 UTC, Dasperal commented on .github/workflows/continuous-integration.yml
> +#         vcpkg install --triplet=${{ matrix.arch.msvc_triplet }} sdl2 sdl2-mixer[core,nativemidi,libmodplug,opusfile] sdl2-net libsamplerate
I'll add NuGet binary cache when I'll be working on this workflow again, probably when it needs to be enabled.

We currently don't require WinXP compatible tool set for vcpkg, simple x86 libraries work for XP.

2023-02-10 07:15 UTC, rfomin commented on .github/workflows/continuous-integration.yml
> +#         vcpkg install --triplet=${{ matrix.arch.msvc_triplet }} sdl2 sdl2-mixer[core,nativemidi,libmodplug,opusfile] sdl2-net libsamplerate
> We currently don't require WinXP compatible tool set for vcpkg, simple x86 libraries work for XP.

It doesn't work for me with Woof. Also vcpkg builds everything with UCRT by default. There is UCRT support on WinXP with older versions of the VC redistributable, but we decided to simply drop support for WinXP.

2023-02-12 10:40 UTC, Dasperal commented
TODOs about SDL2_mixer "plugins" fixed themselves with SDL2_mixer package update in vcpkg