Add an option to enable LTO when available
Russian-Doom/russian-doom pull request #434
Opened 2023-04-07 12:01 UTC by JNechaevsky

Сразу +200 fps (как в танках)! @Dasperal, вам на досмотр, а то очень сложно сделали с .exe и .com, подозреваю что в `src/CMakeLists.txt` не совсем туда впихнуто. Примечательно ещё то, что GCC в MSYS с этим не очень дружит, и может подлагувать и выдать несколько варнингов.

2023-04-08 16:16 UTC, Dasperal requested changes
В целом да, не в те места это впихнуто. И документацию в Compiling.md надо добавить. Пожалуй сам и займусь допиливанием.

Ну и да, LTO может не очень хорошо работать на некоторых компиляторах, так что надо будет проверять что ничего нигде не сломалось.

2023-04-08 16:16 UTC, Dasperal commented on CMakeLists.txt
> +endif()
`CMP0069` was introduced in cmake 3.9, and we require at least 3.15 so `CMP0069` should always exist and be already set to `NEW`.

2023-04-08 16:16 UTC, Dasperal commented on CMakeLists.txt
> +include(CMakeDependentOption)
`CMakeDependentOption` Already included at line 29.

2023-04-08 16:16 UTC, Dasperal commented on src/CMakeLists.txt
> +		)
Any optimizations make step by step debugging really hard, so I think we should disable LTO for debug builds by adding `INTERPROCEDURAL_OPTIMIZATION_Debug OFF` property.

I also think that those properties should be added to all our targets, not just the end ones.
Looks like it is a good time to move all the common properties of the targets to a function like in Woof.

2023-04-08 20:42 UTC, Dasperal commented on src/CMakeLists.txt
> +		)
TODO: Move all the common properties of the targets to a function like in Woof

2023-04-09 12:02 UTC, Dasperal approved these changes

2023-04-09 12:05 UTC, Dasperal commented
По LTO всё сделал.
Ещё включил x64 сборки на MSVC чтобы ругалось на забытые хедеры. Ох, уж этот MinGW и его неявные инклюды.

2023-04-09 12:28 UTC, merged

2023-04-09 12:42 UTC, JNechaevsky commented
Супер, спасибо! М.б. будет смысл в COMPILING дописать про `libunwind` (полностью: `mingw-w64-x86_64-libunwind), она стала требоваться при сборке, для GCC точно. Должно быть что-то типа такого?
```
pacman -S mingw-w64-{i686,x86_64}-{pkgconf,gcc,make,cmake,SDL2{,_net,_mixer},libsamplerate,libunwind} \
       git
```

2023-04-09 13:10 UTC, Dasperal commented
На CI без неё собирается и у меня локально она для MINGW* не установлена. По описанию пакета `A new implementation of a stack unwinder for C++ exceptions`. У нас С++ кода нет, а если она нужна самому GCC, то он её сам притянет как зависимость. Так что указывать не надо, там только то что нужно именно ID.